# Generated by Django 4.2.9 on 2024-07-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="time_last_shipment",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="время последней отправки сообщения"
            ),
        ),
    ]
