# Generated by Django 4.2.9 on 2024-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_newsletter_time_last_shipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("daily", "раз в день"),
                    ("weekly", "раз в неделю"),
                    ("monthly", "раз в месяц"),
                ],
                max_length=20,
                verbose_name="периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("finished", "завершена"),
                    ("created", "создана"),
                    ("launched", "запущена"),
                ],
                max_length=20,
                verbose_name="статус рассылки",
            ),
        ),
    ]
