# Generated by Django 4.2.9 on 2024-08-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_logs_comments_logs_mailing_logs_name_newsletter_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logs",
            name="attempt",
            field=models.CharField(max_length=50, verbose_name="статус попытки"),
        ),
    ]
