# Generated by Django 4.2.9 on 2024-08-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_alter_logs_attempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logs",
            name="response",
            field=models.TextField(
                blank=True, null=True, verbose_name="ответ почтового сервера"
            ),
        ),
    ]
