# Generated by Django 4.2.9 on 2024-08-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0007_client_owner_logs_owner_message_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    (
                        "сan_view_any_mailing_lists",
                        "может просматривать любые рассылки",
                    ),
                    ("can_disable_mailing_lists", "может отключить рассылки"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
