# Generated by Django 4.2.9 on 2024-08-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0008_alter_newsletter_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="почта"),
        ),
    ]
