# Generated by Django 4.2.9 on 2024-08-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0009_alter_client_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Включена/отключена"),
        ),
    ]
