# Generated by Django 4.2.9 on 2024-08-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Введите свой телефон",
                max_length=50,
                null=True,
                verbose_name="Телефон",
            ),
        ),
    ]
