# Generated by Django 4.2.9 on 2024-08-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    (
                        "can_view_the_list_of_users_of_the_service",
                        "может просматривать список пользователей сервиса",
                    ),
                    (
                        "it_can_block_users_of_the_service",
                        "может блокировать пользователей сервиса",
                    ),
                ],
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
